# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: King-Early
    init: |
      curl -fsSL https://deno.land/install.sh | sh
      export DENO_INSTALL="/home/gitpod/.deno"
      export PATH="$DENO_INSTALL/bin:$PATH"
      gp sync-done deno
    command: |
      cd King-Early
      deno task start

  - name: shell
    init: |
      gp sync-await deno
      export DENO_INSTALL="/home/gitpod/.deno"
      export PATH="$DENO_INSTALL/bin:$PATH"
    command: |
      cd King-Early
      deno --version

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: ignore # else every change force a openPreview or openWindow to open.
